#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 09 23:39:09 EST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim UART_RX_TB_behav -key {Behavioral:sim_1:Functional:UART_RX_TB} -tclbatch UART_RX_TB.tcl -protoinst "protoinst_files/bd_f60c.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim UART_RX_TB_behav -key {Behavioral:sim_1:Functional:UART_RX_TB} -tclbatch UART_RX_TB.tcl -protoinst "protoinst_files/bd_f60c.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

