# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HUB75_bus_breakout_0_1/design_1_HUB75_bus_breakout_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_HUB75_bus_breakout_0_1 || ORIG_REF_NAME==design_1_HUB75_bus_breakout_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UART_RX_0_1/design_1_UART_RX_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_UART_RX_0_1 || ORIG_REF_NAME==design_1_UART_RX_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Frame_Clock_Divider_0_1/design_1_Frame_Clock_Divider_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Frame_Clock_Divider_0_1 || ORIG_REF_NAME==design_1_Frame_Clock_Divider_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HUB75_driver_0_3/design_1_HUB75_driver_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_HUB75_driver_0_3 || ORIG_REF_NAME==design_1_HUB75_driver_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_simple_dual_port_ram_0_0/design_1_simple_dual_port_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_simple_dual_port_ram_0_0 || ORIG_REF_NAME==design_1_simple_dual_port_ram_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_simple_rom_0_0/design_1_simple_rom_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_simple_rom_0_0 || ORIG_REF_NAME==design_1_simple_rom_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_simple_dual_port_ram_0_1/design_1_simple_dual_port_ram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_simple_dual_port_ram_0_1 || ORIG_REF_NAME==design_1_simple_dual_port_ram_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fb_writer_0_0/design_1_fb_writer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fb_writer_0_0 || ORIG_REF_NAME==design_1_fb_writer_0_0} -quiet] -quiet

# XDC: /home/adrianna/Git/LED_matrix_driver/LED_matrix_driver.gen/sources_1/bd/design_1/design_1_ooc.xdc
