#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Dec 20 16:43:31 EST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim HUB75_driver_tb_behav -key {Behavioral:led_driver_sim:Functional:HUB75_driver_tb} -tclbatch HUB75_driver_tb.tcl -log simulate.log"
xsim HUB75_driver_tb_behav -key {Behavioral:led_driver_sim:Functional:HUB75_driver_tb} -tclbatch HUB75_driver_tb.tcl -log simulate.log

